### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by mriglobal** [ss-lab-cancerunit/SpiderSeqR#1]
This seems like it'll be very useful. Do you have installation instructions for the primary SpiderSeqR package or is it simply clone the repo and it'll work if I have the other packages?

**Comment by ecballium** [comment]
Thank you for your message. You can clone the repository directly and use it in developer mode, but I think that it is far more streamlined if you install SpiderSeqR directly from github by running:

devtools::install_github("ss-lab-cancerunit/SpiderSeqR")

Following that, please run one of the setup functions: startSpiderSeqR() or startSpiderSeqRDemo("path/to/dir"). These functions setup the necessary database connections (and the latter donwnloads the full database files).
The setup process is outlined in the vignette ([Quick_SpiderSeqR](https://github.com/ss-lab-cancerunit/SpiderSeqR/blob/master/vignettes/Quick_SpiderSeqR.Rmd)), but I have added the above code for ease of installation from github.
Let me know if you have any other questions
